### ISSUE TITLE
ERROR: code_auth_token.status:  401 {"error":"invalid_request","error_description":"invalid session"}

### ISSUE THREAD

**Issue by tpimh** [VKCOM/vk-tunnel-client#6]
`ERROR: code_auth_token.status:  401 {"error":"invalid_request","error_description":"invalid session"}` after successully authorizing VK Tunnel Client app and pressing `Enter`.

**Comment by ilyapishchulin** [comment]
Try:

rm ~/.config/configstore/@vkontakte/vk-tunnel-client.json`
or
del %username%\.config\configstore\@vkontakte\vk-tunnel-client.json

**Comment by MrFireFrog** [comment]
Такая же проблема при запуске на ubuntu 
["2021-02-21T14:27:12.062Z"] ERROR: code_auth_token.status:  401 {"error":"invalid_request","error_description":"invalid session"}
хотя все авторизовано

**Comment by ilyapishchulin** [comment]
Попробуй команду выше

**Comment by MrFireFrog** [comment]
Пробовал. Не помогает. на macOS все работает отлично. на ubuntu 18 не получается. 
Запускаю на ubuntu, копирую ссылку, на маке в браузере авторизовывал , а ubuntu не видит авторизацию

**Comment by ilyapishchulin** [comment]
Запиши видео с очисткой хранилища и запуском тунеля

**Comment by MrFireFrog** [comment]
данный файл не создается 
по пути в директории только один  файл:
`vk-tunnel.json`

**Comment by ilyapishchulin** [comment]
rm ~/.config/configstore/@vkontakte/vk-tunnel.json

**Comment by MrFireFrog** [comment]
root@p590428:/home# npm install @vkontakte/vk-tunnel -g
npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
/usr/bin/vk-tunnel -> /usr/lib/node_modules/@vkontakte/vk-tunnel/bin/vk-tunnel

> bufferutil@4.0.3 install /usr/lib/node_modules/@vkontakte/vk-tunnel/node_modules/bufferutil
> node-gyp-build


> utf-8-validate@5.0.4 install /usr/lib/node_modules/@vkontakte/vk-tunnel/node_modules/utf-8-validate
> node-gyp-build

+ @vkontakte/vk-tunnel@0.0.16
added 89 packages from 51 contributors in 7.841s
root@p590428:/home# 




Все так же. Лог установки vk-tunnel выше

**Comment by ilyapishchulin** [comment]
Уязвимость исправлена, сейчас должно быть всё хорошо

**Comment by fax1ty** [comment]
Всё ещё не работает. После rm всё повторяется.
P.S. Запускаю команду на VPS без GUI. Открываю ссылку в своём браузере

**Comment by ilyapishchulin** [comment]
ip открытия соединения должен совпадать с ip получения токена, поэтому у вас не работает
